### ISSUE TITLE
Exception: Undefined array key "id_token"

### ISSUE THREAD

**Issue by FortuneV13** [dcblogdev/laravel-xero#73]
Looks like the token is always timing out and no refreshing. Command is running every five minutes as per the docs.

**Comment by dcblogdev** [comment]
confirmed, I'm looking into this.

**Comment by dcblogdev** [comment]
so when the token is expired and a refresh is attempted an invalid grant is returned, I've set it that is in a console the token will be deleted and an exception will be thrown with the message "Token has expired, please re-authenticate"

Otherwise if using a browser the token will be deleted and redirected back to the Xero to authenticate.

testing this flow.

**Comment by dcblogdev** [comment]
This should be resolved now in https://github.com/dcblogdev/laravel-xero/releases/tag/v1.1.11
